# parte P: achados 'pedro' (41). Todos viram pergunta T com recomendacao, ou acao minha ja coberta.
P = {}
def p(i, t, rec, status='pedroDecide', acao='aguarda Pedro'):
    P[i] = {'status': status, 'perguntaPedro': t, 'recomendacao': rec, 'acao': acao}

p('espadachim-oportunista', 'T5', '"PMA" definido no Sistema pela D29. "Nesta rodada" = neste turno, porque a PMA é por turno. Com isso a técnica funciona como está.')
p('espadachim-coragem-liquida', 'T7', '+1 na perícia Movimento: as outras 5 marcas do Espadachim dão perícia.')
p('notacao-1x-dia', 'T5', 'Trocar "1x/Dia" por "1x/Descanso Longo" nas ultimates e no cabeçalho do Tier 3 das 7 classes. É só texto: a ficha já recarrega no descanso longo (L29).')
p('espadachim-recurso', 'T6', 'Preciso do texto (nome, máximo, ganho, perda). Até lá a ficha mostra um contador livre, com nome e atual/máx editáveis.')
p('batedor-ocultar-se', 'T8', 'Custo final 1 ação. Corrigir "ao invés de 2" para "ao invés de 3", o custo atual de Esconder.')
p('batedor-homem-de-negocios', 'T8', 'A frase está cortada no próprio Notion ("Você possui um disturbio de mat"). Preciso do resto.')
p('batedor-senhor-das-linhas', 'T8', 'Flanqueio não existe no Sistema: tirar "Não pode ser flanqueado" ou criar a regra. A armadilha causa Perfurante.')
p('batedor-desenhar-mapa-de-exploracao', 'T8', 'O "-" vazio está no Notion: faltou um 3º benefício? O mapa não é item do Bazar; a ficha o adiciona como item manual Incomum.')
p('batedor-artista-apaixonado', 'T8', '"Mercadoria Incomum" muda o quê, se o mapa já é Incomum? Sugestão: vende pelo preço de Incomum do Bazar. Se não mudar nada, a técnica sai ou ganha outro efeito.')
p('brutalista-muralha-viva', 'T9', 'Texto proposto (L19): "Some +1 à rolagem de Defender para cada grau de treinamento (Treinado +1, Experiente +2, Mestre +3, Lendário +4)." É a tradução exata do "3 em 3" antigo, que dava +1 por grau acima do normal.')
p('brutalista-frenesi', 'T9', '"No nível 1" → "no nível 2": o Tier 1 só abre no 2. Os 2 usos no nível 3 ficam.')
p('brutalista-frenesi-2', 'T9', '"Descontrolado" como adjetivo, não a condição, que faria o Brutalista atacar aliados. Para a ficha travar algo, preciso da lista "paciência ou concentração"; o mínimo seria "não conjura nem sustenta magias".')
p('brutalista-investida', 'T10', 'L20: renomear para "Atropelar". Conta como o Mover do turno. "Caidos" → Caído (corrijo junto).')
p('brutalista-contador-de-corpos', 'T9', 'A nota do asterisco não existe no Notion. Sugestão: "brutalmente" = matar com acerto crítico ou pelo Finalizar.')
p('brutalista-imortal', 'T9', 'Reescrever: "Ao cair a 0 ou menos de Saúde, pode, como ação livre, ficar com 1 de Saúde em vez de entrar em Morrendo. Ao fazer isso, ganha +1 de Exaustão."')
p('teurgo-encadeamento', 'T11', 'É exceção ao "1 magia por turno": escrever isso, como o Receptáculo Perfeito escreve. 3 Stamina por uso.')
p('teurgo-manifestacao-do-patrono', 'T11', 'As CDs sem número viram "contra sua CD" (D57).')
p('teurgo-manifestacao-do-patrono-2', 'T11', '"Banido" fica efeito da ultimate (como Marcado e Endividado), não condição nova.')
p('teurgo-manifestacao-do-patrono-3', 'T11', 'Sorteio com 1d6 na ordem da lista.')
p('teurgo-patrono-primordial-2', 'T11', 'Não soma Marca da Vhelor. A Seiva do patrono não é o item do Bazar, e somar tiraria 10 de Éter máximo do próprio devoto na Marca 2.')
p('teurgo-recurso', 'T6', 'Mesma pergunta do Espadachim: nome e regra, ou "o recurso é o Éter" (o que o contrato dizia).')
p('teurgo-receptaculo-perfeito', 'T11', '"Ao chegar em 50%" → "ao ultrapassar 50%" (PD17). A Casca Rachada dobra esse limite também. Morrer em vez de passar o personagem ao mestre é regra da ultimate e fica.')
p('teurgo-devoto', 'T11', 'O requisito é Patrono Primordial ou Barganha Primordial? O "Preço do Pacto" é do Patrono Primordial.')
p('monge-forma-do-vazio', 'T12', '"1d10 <5 acerta" dá 40%, não 50%: trocar para "≤5 acerta". "Ataques físicos" = ataques de arma e desarmados, de qualquer tipo de dano.')
p('monge-perda-de-fluxo-ultimates', 'T12', 'Acrescentar "exceto quando o texto de uma técnica diz que você perde Fluxo" a "Você não pode perder fluxo de nenhuma outra forma" (Insurgência, Fusão Primal). A frase seguinte, que diz que o custo em Fluxo é só requisito, fica como está.')
p('monge-queda-suave', 'T12', 'Por 1 minuto, quedas de até 30 m não causam dano a você e a até 5 criaturas tocadas; acima de 30 m, o dano cai 5 × Nível. Dano de queda é do mestre (o Sistema não define).')
p('monge-transcendencia', 'T5', 'Resolvido pela definição de PMA no Sistema (T5). "Durante essa rodada" = neste turno.')
p('alquimista-cartucho-arcano', 'L18', 'L18 já respondida ("vale o primeiro"): gravo "do seu nível ou menor" no Notion.', status='resolvido', acao='Notion (Alquimista)')
p('alquimista-tita', 'T10', 'L20: renomear a ação do Titã para "Avalanche".')
p('alquimista-curandeiro-incansavel', 'T13', '"Que estava com 0 de Saúde e remover a condição morrendo" → "que estava Morrendo e remover a condição".')
p('alquimista-essencia-eterea', 'T13', '"Incorpóreo" fica efeito do item, descrito no CSV, não condição nova.')
p('artilheiro-municao-especial', 'T14', 'Alinhar a "10 = 1 bugiganga", como toda munição, a menos que o peso maior seja proposital.')
p('artilheiro-tiro-carregado-2', 'T5', '"Margem de Crítico" → "Margem de Ameaça" (normalização de termo).')
p('artilheiro-artesao-de-municao', 'T5', '"Flecha" → "Virotes/Flechas" e "Adagas de lançamento" → "Conjunto de Arremesso" (nomes do Bazar).')
p('automato-sensor-de-proximidade', 'T5', '"Não pode ser surpreendido" → "Não pode ser Desprevenido".')
p('automato-achar-tecnologias-em-lojas', 'T15', 'O d12 não fecha com a lista (6 não compráveis no Tier 1 + 9 compráveis). Sugestão: 1d10 sobre as 9 compráveis na ordem da lista, rerolando o 10 e os repetidos.')
p('gruto-lingua-bifurcada', 'T15', 'Preciso da definição de "Criaturas Predáveis". Sugestão: Dryads e criaturas menores que você.')
p('raca-corrompido', 'T15', 'Reescrever pelo sinal da tabela: "Adversidades (custo +) são permanentes; poderes (custo −) podem ser reorganizados no descanso longo."')
p('corrompido-mente-fraca', '-', 'Sem ação no texto: a ficha casa por id, não por nome, e a colisão com a Dor do Abismo some. Renomear é opcional.', status='resolvido', acao='ficha: casar por id (G14)')
p('origem-cacador-itens', 'T16', '"1 Arma Simples" → "1 Arma Distância Simples" (arco do caçador).')
p('origem-mineiro-itens', 'T16', 'Parece cópia do Lenhador. Trocar "Madeira Comum" por "Cobre" (Material Ordinário mineral do Bazar).')
